create table table_user (id int8 generated by default as identity, username varchar(255), email varchar(255), password varchar(255), primary key (id));
create table table_product (id int8 generated by default as identity, name varchar(255), amount int, description varchar(255), primary key (id));
